### ISSUE TITLE
Have description for blog posts be specific to the blog post

### ISSUE THREAD

**Issue by ddgenome** [MonsantoCo/engineering-blog#34]
This is @philcryer 's idea.

Currently the description for each blog post is generic for the site.

```html
<meta name="description" content="The engineers of Monsanto produce code that powers agricultural products that support farmers all around the world. Our goal of sustainable agriculture mirrors the way we present our ideas and code to the world.">
```

Perhaps we could make the description the description frontmatter field if it is present, subtitle if not. If neither is present, we could use a snippet of the text.

Basically, could we make it's summary in Slack look better? See #eng-blog channel for more details.

**Comment by chrisshafer** [comment]
(Solved)[https://github.com/MonsantoCo/engineering-blog/pull/35] 

Meta description tag will contain page description if present in the front matter, otherwise the title and subtitle separated by hyphen.

I briefly looked into using an auto summary service like TextTeaser , but I wasn't happy with the results I got. Its hard to beat an actual human.

Unfortunately some of our posts don't start with sentences that would work well in a description, or they are polluted with markup, so that's off the table as well.
