### ISSUE TITLE
Add rss feed.

### ISSUE THREAD

**Issue by serkanh** [MonsantoCo/engineering-blog#55]
I came across the site while looking for a solution for etcd cluster in AWS. Seems like there is alot of good content generated by you guys but when i try to subscribe to it, rss was not available. Looks like you guys are using jekyll so this https://github.com/snaptortoise/jekyll-rss-feeds repo can help to add rss functionally.

**Comment by chrisshafer** [comment]
Thanks for bringing this to our attention! It appears that we don't have an auto discovery link in our header. Our 10 latest articles are available as an RSS feed here : http://engineering.monsanto.com/feed.xml.  

RSS auto discovery should be fixed by pull https://github.com/MonsantoCo/engineering-blog/pull/56, once its merged.

http://www.rssboard.org/rss-autodiscovery
